transition to vite

diff --git a/domain-story-modeler-thesis/Dockerfile b/domain-story-modeler-thesis/Dockerfile
--- a/domain-story-modeler-thesis/Dockerfile
+++ b/domain-story-modeler-thesis/Dockerfile
@@ -1,16 +1,22 @@
-# Build stage
-FROM node:16-alpine AS build-stage
+FROM node:19-alpine AS base
+
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json ./
-COPY package-lock.json ./
-RUN npm ci
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-
 RUN npm run bundle
 
-
-# Runtime stage
-FROM nginx:1.22-alpine
-COPY --from=build-stage /app/dist /usr/share/nginx/html
+FROM nginx:1.22-alpine AS runtime
+COPY --from=builder /app/dist /usr/share/nginx/html
